### ISSUE TITLE
Page Banner Images

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#16]
I have smaller sizes of the banners so you can try to fix the extra large appearance of the banners on desktop, as discussed previously. Is that what you would need to do so? If so, reply here with a comment and I will add them to the Dropbox.

**Comment by alnabid** [comment]
waiting on reworked images for desktop

**Comment by muhachris297** [comment]
@alnabid new sized banners are in the works.

**Comment by muhachris297** [comment]
@alnabid  These were uploaded to the website and it looks like the changes were made. Please close this as completed if it is complete.
