### ISSUE TITLE
Automatic Numbering

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#18]
Please add automatic numbering for all review sliders as we discussed.
Please also remove manual numbering from all other reviews in all sliders.

**Comment by muhachris297** [comment]
@alnabid I want to be able to copy and paste the code for this in any page for anything. Applying it to the reviews is to be done in the manner we discussed when this issue is not on hold. For now, just do it the other way of which will work fine for now. Then, move the newsy Gunawan Guan Review where it is supposed to be in the code.

**Comment by alnabid** [comment]
#19 
reference for the new fiverr review.

**Comment by muhachris297** [comment]
@alnabid would this work?

<ul>
  
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
  
  <li>...</li>
  <li>Sixty</li>
</ul>

<script>
  // JavaScript to generate numbers in words and sort them
  // Using num2words.js (https://github.com/saumya/num2words)
  var numbersInWords = [];
  for (var i = 1; i <= 60; i++) {
    numbersInWords.push(num2words(i));
  }
  numbersInWords.sort();
  
  // Update list items with sorted numbers in words
  var listItems = document.querySelectorAll('ul li');
  for (var i = 0; i < listItems.length; i++) {
    listItems[i].textContent = numbersInWords[i];
  }
</script>

</body>
</html>

**Comment by muhachris297** [comment]
@alnabid completed this as required.
