### ISSUE TITLE
Add new Gunawan Guan Review 3 to Fiverr Buyer Slider

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#19]
Please add the new Gunawan Guan 3 review image to the fiverr buyer review slider after gunawan guan review 2.

**Comment by alnabid** [comment]
its added as last. it will be possible to add it right after 2nd review without hustle when we do the automation

**Comment by muhachris297** [comment]
> its added as last. it will be possible to add it right after 2nd review without hustle when we do the automation 

Ok, @alnabid, please reference this issue in the automatic numbering issue.

**Comment by muhachris297** [comment]
@alnabid completed this as requested.
