### ISSUE TITLE
Bookmarks to Add

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#21]
There are new bookmarks for you to add in the bookmarks-add document.

**Comment by muhachris297** [comment]
The bookmarks for Computer Optimization need to be sorted alphabetically by title. I tried sorting alphabetically in Word but it did it by address (URL), not by the name of the bookmark. Maybe you can get that to work some how or find an alternative automatic solution to reduce the time this task will take.

**Comment by alnabid** [comment]
Finding an automatic solution will take more time to build. Ill sort it out manually.

**Comment by muhachris297** [comment]
> Finding an automatic solution will take more time to build. Ill sort it out manually.
> 
> 

if you want to sort it manually that is fine, but in the future, is there a way you can develop an alphabetical sorting solution that we can implement in any file for anything? The same goes for the automatic numbering process for the reviews?

@alnabid  Can you reference the alphabetical order tasks in a new issue and put it on hold?

**Comment by alnabid** [comment]
Can't. Has to be structure-specific. All content in your website is totally different than the content of bookmarks. 

If we're gonna add auto-ordering for bookmarks. Every other section that youre gonna auto-order the same way in any page HAS to have the structure like bookmarks. 

It's not like this is something I specifically can't do. It's just not possible. The auto-ordering will only target the same kind of elements that it's supposed to target. We need different functionalities with the same feature for different things in different pages to make it widely possible.

for now, i can do auto-order for bookmarks but that's gonna be expensive too.

**Comment by muhachris297** [comment]
> Can't. Has to be structure-specific. All content in your website is totally different than the content of bookmarks. 
> 
> 
> 
> If we're gonna add auto-ordering for bookmarks. Every other section that youre gonna auto-order the same way in any page HAS to have the structure like bookmarks. 
> 
> 
> 
> It's not like this is something I specifically can't do. It's just not possible. The auto-ordering will only target the same kind of elements that it's supposed to target. We need different functionalities with the same feature for different things in different pages to make it widely possible.
> 
> 
> 
> for now, i can do auto-order for bookmarks but that's gonna be expensive too. 

@alnabid ok, I will make the changes to the directions for the bookmarks file to specify where those bookmarks should be added to/moved to. I will message you on Discord, so I will close this issue as complete.
