### ISSUE TITLE
Revisions 2-16-24

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#27]
@alnabid 

1. Review Responses needs to be renamed to Google Reviews Responses

2. Google Reviews Responses will be below the Google Review

3. Google Reviews and Google Responses will have the automatic numbering too.

4. Button colors need to be specified once in code, not in each individual file IF that is how it currently works.

**Comment by muhachris297** [comment]
task 4 was completed by @alnabid.

**Comment by alnabid** [comment]
Done all of these, and pushed.
