### ISSUE TITLE
Dropbox 2-16-2024

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#28]
@alnabid please complete all tasks in the Dropbox pages-changes document for this website.

**Comment by muhachris297** [comment]
@alnabid I have pushed all changes I made on my own, the rest are up to you.

**Comment by alnabid** [comment]
Dropbox pages changes includes the statistics page/feature request. That is on hold. But I see there are 2 new bookmarks to add, should I do that?

**Comment by muhachris297** [comment]
> Dropbox pages changes includes the statistics page/feature request. That is on hold. But I see there are 2 new bookmarks to add, should I do that?

Yes, statistics is to remain on hold. Please send a screenshot of the bookmarks you are referring to.

**Comment by muhachris297** [comment]
@alnabid I see the bookmarks (two) are only the first page of the document. There are additional pages with additional bookmarks that need to be added. Please quote the cost of that and I will tell you when to proceed by removing the on hold label. I am putting it on hold for now but may complete this myself, remove the on hold label, and close as completed saying I completed it on my own.
Thank you.

**Comment by muhachris297** [comment]
@alnabid I completed all bookmarks tasks. Please complete the remaining tasks that are not on hold and then close this issue as completed. Thanks.

**Comment by muhachris297** [comment]
@alnabid what is the status of completing the remaining tasks? Please reply with what tasks you have left to do or close this issue if it is completed. If preferable, do not reply with tasks left, just reply that you are still working and then close this issue when those remaining issues are completed.

**Comment by alnabid** [comment]
I don't see any tasks to do in dropbox.
