### ISSUE TITLE
Announcement Feature

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#29]
@alnabid As we discussed, we will be adding an announcement banner that we can hide when it is not being used. It needs to be what is used on Website Template 3. If there is a way this can be set to only appear when it has text in it, then that will be a requirement for this task to be completed. I do not have any announcements to add right now. The attached image is a screenshot of the said announcement banner from Website Template 3.
![image](https://github.com/chrismuha/chrismuha/assets/89660766/4c5e05b1-45e0-4ed9-b7bd-d0d21c08a46c)

**Comment by alnabid** [comment]
Done. Please close the issue if you don't have anything more to add to this task.

**Comment by muhachris297** [comment]
@alnabid I think you did anything additional I asked, if that is correct, please close this issue.
