### ISSUE TITLE
Table Issue for newly added Website Development Service

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#30]
@alnabid I just noticed this issue for the table that happens only for the service I added for Website Development. Please fix this issue, I have attached a screenshot of the issue.
![Screenshot 2024-02-20 at 9 16 46 PM](https://github.com/chrismuha/chrismuha/assets/89660766/31137004-30c4-4f69-8779-4c3f0a60009b)
.

**Comment by muhachris297** [comment]
24/7 service wording is too close to the edge.
@alnabid Is there a way you can make the table automatically size any new services that are added?

**Comment by alnabid** [comment]
they do automatically size. 

Place the single-ftc-sec div inside a single-ftc-pos div which has to be right inside mcr-ftc div

like this

```html
<div class="container">
    <div class="mcr-ftc">
        <div class="single-ftc-pos">
            <div class="single-ftc-sec">
                this is an example of a text of just one box horizontally
            </div>
        </div>
        <div class="single-ftc-pos">
            <div class="single-ftc-sec">
                this is another box below the box above.
            </div>
            <div class="single-ftc-sec">
                and this has 2 boxes.
            </div>
        </div>
    </div>
</div>
```

Visualized: 
![image](https://github.com/chrismuha/chrismuha/assets/54846794/84a42d7a-9027-4826-bb5f-8861bd18dd79)

Anyway your problems above has been fixed. So im closing this issue.
