### ISSUE TITLE
Unnecessary Content on Hiring, Book, and Policies Pages

### ISSUE THREAD

**Issue by muhachris297** [chrismuha/chrismuha#31]
@alnabid There are the reviews sliders, tables, and buttons we use on the Hiring, Book, and Policies pages that we do not need there. The buttons that should be removed on those pages are the schedule, pay bill, check gift card balance, down payment, call us, text us, and email us buttons. The reviews sliders and tables should be removed on those pages too, if present.

**Comment by alnabid** [comment]
Done.

**Comment by muhachris297** [comment]
@alnabid forgot to mention removing the social buttons, please remove those too.

**Comment by alnabid** [comment]
Done
